---
title: "SDS 192 Mini-Project 2"
subtitle: "SDS 192"
author: 
- name: Author One
  affiliation: Smith College
- name: Author Two
  affiliation: Smith College
- name: Author Three
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE
)
library(tidyverse)
library(lubridate)

```

```{r import, include=FALSE}
# Import the data here
```

```{r clean, include=FALSE}
# Write code to complete steps 1-3 below, and store your results in a new data frame. I recommend a data frame with the word "_cleaned" appended to the variable name.

# Step 1: Create a new column called physician_full_name with the physician's full name (don't include middle initial or suffix; sometimes the same physician will include it in some reports and not others, and the goal is to standardize names here.)

# Step 2: Standardize the formatting of any text variables you plan to use in the assignment by converting their text to uppercase. Note that you may need to come back to this step as you are working through your analysis. 

# Step 3: Convert the date_of_payment column and payment_publication_date columns to date format

```

# Analysis

```{r analysis}
# Start your analysis here. Create new code chunks for each table you plan to produce. 
```

# Report

Compose your report here...



